### ISSUE TITLE
Android request not working

### ISSUE THREAD

**Issue by PrasannaT** [pierrestudios/territory-api#1]
Hi I just trying to use this Rest Api for Android App. but this APIs not responding for android app. But Postman requests working properly.

**Comment by pierrestudios** [comment]
Hi.

Can you describe the specific error you are getting with Android.

**Comment by PrasannaT** [comment]
It says connection refused.

**Comment by PrasannaT** [comment]
There are only issues with when working on localhost hosting, but server hosting working fine. thanks
